version: "3"

services:
  db:
    container_name: "visualnovel_db"
    image: postgres:10.5
    volumes:
      - ./database_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
